version: "3.8"

volumes:
  postgres_data:


services:
  db:
    image: postgres:15.4-alpine
    container_name: edgame-bot-db-stage
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    image: ghcr.io/studio-yandex-practicum/edgame_bot:latest
    container_name: edgame-bot
    restart: always
    volumes:
      - ./logs:/EdGame_bot/logs/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
