"""kid password

Revision ID: c4c144c103ab
Revises: 539226c89111
Create Date: 2023-12-05 13:05:28.353989

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4c144c103ab'
down_revision: Union[str, None] = '539226c89111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_pass', sa.String(length=256), nullable=False),
    sa.Column('counsellor_pass', sa.String(length=256), nullable=False),
    sa.Column('methodist_pass', sa.String(length=256), nullable=False),
    sa.Column('master_pass', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    # ### end Alembic commands ###
