"""fix foreign keys

Revision ID: 5f4c76b9bc62
Revises: cade7b5e1ef7
Create Date: 2023-10-14 16:30:38.525740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4c76b9bc62'
down_revision: Union[str, None] = 'cade7b5e1ef7'# '90d97e8be984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_captain_id_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'captain_id')
    op.add_column('users', sa.Column('captain_of_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_team_captain_id', 'users', 'team', ['captain_of_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_team_captain_id', 'users', type_='foreignkey')
    op.drop_column('users', 'captain_of_team_id')
    op.add_column('team', sa.Column('captain_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('team_captain_id_fkey', 'team', 'users', ['captain_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
