"""add_tables_team_and_category

Revision ID: d1e54589437b
Revises: f277b59882ea
Create Date: 2023-10-08 14:50:15.484412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e54589437b'
down_revision: Union[str, None] = 'f277b59882ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('achievements', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievements', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'team_id')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_column('achievements', 'category_id')
    op.drop_table('team')
    op.drop_table('category')
    # ### end Alembic commands ###
