"""add team field to Users and AchievementStatus

Revision ID: 9ecb7abbc687
Revises: 42cdcca7865e
Create Date: 2023-10-14 12:16:20.997294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecb7abbc687'
down_revision: Union[str, None] = '42cdcca7865e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_achievements', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('users_achievements_team_id_cascade_fkey', 'users_achievements', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users_achievements', 'user_id', type_=sa.BigInteger())
    op.add_column('users', sa.Column('captain_of_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_team_captain_id', 'users', 'team', ['captain_of_team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_achievements_team_id_cascade_fkey', 'users_achievements', type_='foreignkey')
    op.drop_column('users_achievements', 'team_id')
    op.alter_column('users_achievements', 'user_id', type_=sa.Integer())
    op.drop_constraint('user_team_captain_id', 'users', type_='foreignkey')
    op.drop_column('users', 'captain_of_team_id')
    # ### end Alembic commands ###
