"""add field captain to Team

Revision ID: cade7b5e1ef7
Revises: 9ecb7abbc687
Create Date: 2023-10-14 12:28:58.852325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cade7b5e1ef7'
down_revision: Union[str, None] = '9ecb7abbc687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('captain_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('team_captain_id_fkey', 'team', 'users', ['captain_id'], ['user_id'], ondelete='SET NULL')
    op.drop_constraint('users_achievements_team_id_fkey', 'users_achievements', type_='foreignkey')
    op.create_foreign_key('users_achievements_team_id_cascade_fkey', 'users_achievements', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users_achievements', 'user_id', type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_achievements_team_id_cascade_fkey', 'users_achievements', type_='foreignkey')
    op.create_foreign_key('users_achievements_team_id_fkey', 'users_achievements', 'team', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('team_captain_id_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'captain_id')
    op.alter_column('users_achievements', 'user_id', type_=sa.Integer())
    # ### end Alembic commands ###
