"""Adding Password class

Revision ID: b44a11bc64cf
Revises: 9ecb7abbc687
Create Date: 2023-10-23 15:18:05.023390

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b44a11bc64cf'
down_revision: Union[str, None] = '9ecb7abbc687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_pass', sa.String(length=256), nullable=False),
    sa.Column('counsellor_pass', sa.String(length=256), nullable=False),
    sa.Column('methodist_pass', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    # ### end Alembic commands ###
