"""Initial migration

Revision ID: adc94bc15d30
Revises: 
Create Date: 2023-08-13 18:40:46.975300

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'adc94bc15d30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('achievement_type', sa.String(), nullable=False),
    sa.Column('achievement_score', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('users_achievements',
    sa.Column('user_achievement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.achievement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_achievement_id')
    )
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('user_achievement_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_achievement_id'], ['users_achievements.user_achievement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('users_achievements')
    op.drop_table('users')
    op.drop_table('achievements')
    # ### end Alembic commands ###
