name: Run tests

on:
  pull_request:
    branches:
      - dev
      - master

env:
  DB_ENGINE_TEST: postgresql+psycopg2
  POSTGRES_USER_TEST: edgame-bot-test
  POSTGRES_PASSWORD_TEST: somepassword
  DB_HOST_TEST: localhost
  POSTGRES_DB_TEST: edgame-bot-test
  POSTGRES_PORT_TEST: 5432

jobs:
  migrations:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB_TEST}}
          POSTGRES_USER: ${{env.POSTGRES_USER_TEST}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD_TEST}}
        ports:
          - 5432:5432
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      -
        name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Run test
        run: pytest